select * from mysql.user;
SELECT user, host FROM mysql.user;
SELECT * FROM mysql.help_topic;
SELECT help_topic_id, help_category_id, url FROM mysql.help_topic;
show databases;
use quotes_db;
select quotes_db();
use chipotle;
select database();
use quotes_db;
select database();